name: Publish Python package (easykey)

on:
  push:
    tags:
      - "python-v*"
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Tag to build from (defaults to current commit)"
        required: false

permissions:
  contents: read

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade packaging tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build twine

      - name: Build wheel and sdist
        run: |
          python -m build

      - name: Twine check
        run: |
          python -m twine check dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/python-v') || github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          verbose: true


